### ISSUE TITLE
Self hosting??

### ISSUE THREAD

**Issue by Inside4ndroid** [Ryuk-me/Torrent-Api-py#15]
can i install this on my dedicated server without having to use redis or deploying to roku??

i have tried installing but i get an error for fastapi-cache2

`root@server:~/Torrent-Api-py# pip3 install -r requirements.txt
Collecting aiohttp (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f6/3b/2e3b8a5b19cdceb532c61d83077a09afe1f120cb876fb771b0ce577cc0ea/aiohttp-3.8.1-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 799kB/s
Collecting fastapi (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/61/0f/427f0af121b226e62237e430f5bf4485e0ae1565b3f5b782613b59f30abc/fastapi-0.78.0-py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 5.9MB/s
Collecting uvicorn[standard] (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a0/bb/1f93757efc22e6e047021dd10255ae471e7930cfc1676ad18b9c70de48e5/uvicorn-0.17.0-py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 6.1MB/s
Collecting beautifulsoup4 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/9c/d8/909c4089dbe4ade9f9705f143c9f13f065049a9d5e7d34c828aefdd0a97c/beautifulsoup4-4.11.1-py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 5.4MB/s
Collecting aioredis (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/9b/a9/0da089c3ae7a31cbcd2dcf0214f6f571e1295d292b6139e2bac68ec081d0/aioredis-2.0.1-py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 4.8MB/s
Collecting cloudscraper (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/85/4e/96e23b05beaa2fea2972294d7c0d73d0f055822bdb4a8ffa5f88293820ff/cloudscraper-1.2.60-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 5.8MB/s
Collecting fastapi-cache2 (from -r requirements.txt (line 7))
  Could not find a version that satisfies the requirement fastapi-cache2 (from -r requirements.txt (line 7)) (from versions: )
No matching distribution found for fastapi-cache2 (from -r requirements.txt (line 7))
`

any help would be great thanks :)

**Comment by devillD** [comment]
Try updating packages & pip.
Using docker would be the best idea, if you wanna host on vps.
