### ISSUE TITLE
Search limit doesn't working on nyaasi

### ISSUE THREAD

**Issue by devillD** [Ryuk-me/Torrent-Api-py#16]
Checked several times.
**Using Limit:** https://torrents-api-py3.herokuapp.com/api/v1/search?site=nyaasi&query=your%20name&limit=20&page=1
**Without Limit:** https://torrents-api-py3.herokuapp.com/api/v1/search?site=nyaasi&query=your%20name&limit=0&page=1
Showing 75 results in the both, although using the search limit.

**Comment by Ryuk-me** [comment]
fixed it https://github.com/Ryuk-me/Torrent-Api-py/commit/0da531c8c4b23de507a9df9f79c049434cfaf88c
