### ISSUE TITLE
{"error":"website blocked change ip or domain"}

### ISSUE THREAD

**Issue by ShebeerPrince** [Ryuk-me/Torrent-Api-py#25]
This query `https://torrents-api-py3.herokuapp.com/api/v1/search?site=bitsearch&query=avengers&page=1` gives an error `{"error":"website blocked change ip or domain"}`.

Noticed the above error occurs when the query is a single word. The query gave true results when I tried manually in the BitSearch website, but it gives an error when the same is down through the API.

Also, API gives true results when any extra word is added and the query is modified to a non single word like "_avengers 2021_". 

Anyway, thanks a lot for the API. Brilliant work mate 🙌🏽

**Comment by Ryuk-me** [comment]
@ShebeerPrince sorry for the delay fixed it https://github.com/Ryuk-me/Torrent-Api-py/commit/bac1f0e60a4fe3a218baba76b1d2e7198d37ca1c

**Comment by ShebeerPrince** [comment]
> @ShebeerPrince sorry for the delay fixed it https://github.com/Ryuk-me/Torrent-Api-py/commit/bac1f0e60a4fe3a218baba76b1d2e7198d37ca1c

Great.
