### ISSUE TITLE
api key for description of torrent?

### ISSUE THREAD

**Issue by arijit4** [Ryuk-me/Torrent-Api-py#27]
would be great if I also had the description for the torrent as in [the avengers torrent](https://kickasstorrents.to/doctor-strange-in-the-multiverse-of-madness-2022-720p-bluray-x264-nezu-t5328765.html)

```
Doctor Strange in the Multiverse of Madness (2022)

Release ........: Doctor.Strange.in.the.Multiverse.of.Madness.2022.720p.BluRay.x264-NeZu
Release Number .: 1048
Release Date ...: 17.07.2022

Movie Info
IMDb ....: https://www.imdb.com/title/tt9419884/
Rating ..: 7.0/10 from...
```

**Comment by Ryuk-me** [comment]
@arijit4 these kinds of data are unpredictable some torrent may have those field some may not and also the number of lines in the description are always changing, which make it hard to scrap and put value in the right key.
Although I will give it a try.

**Comment by arijit4** [comment]
@Ryuk-me hey! Did you manage to do that?🥹🥹

**Comment by Ryuk-me** [comment]
@arijit4 data was inconsistent, so it is was not possible to add key value pair for the data, so i wasn't able to implement it but i will add imdb id so you can fetch those data from imdb.Will surely implement imdb id support for the available websites in few days
