### ISSUE TITLE
"Internal Server Error" returned when running example URLs

### ISSUE THREAD

**Issue by DrummerBoyQ** [Ryuk-me/Torrent-Api-py#31]
Thank you for this great api.

For the last few days I'm receiving "Internal Server Error" when running the herokuapp.com example URLs you provided (links below) 
Not sure if the timing coincided with recent Redis shut down (but its my understanding dependencies have already been removed)

https://torrents-api-py3.herokuapp.com/api/v1/all/search?query=avengers&limit=5
https://torrents-api-py3.herokuapp.com/api/v1/search?site=1337x&query=eternals

**Comment by Ryuk-me** [comment]
that is why because apis are not hosted links will be updated soon.
