### ISSUE TITLE
magnet/hash is not available?

### ISSUE THREAD

**Issue by shreyash729** [Ryuk-me/Torrent-Api-py#43]
https://6howpgdphtrt752l4oksuieqyu0qcqfu.lambda-url.ap-southeast-2.on.aws/api/v1/search?site=1337x&query=eternals
not getting torrent magnet and hash value is json response

**Comment by Ryuk-me** [comment]
Attaching reference image for the same and closing this issue.

![image](https://github.com/Ryuk-me/Torrent-Api-py/assets/55330971/712f4928-8063-49be-aaf5-59c0ef2bc6e4)
