### ISSUE TITLE
yts have no magnet link

### ISSUE THREAD

**Issue by aston314** [Ryuk-me/Torrent-Api-py#48]
In json file.

**Comment by aston314** [comment]
1337x too.

**Comment by Ryuk-me** [comment]
@aston314 will check it

**Comment by aston314** [comment]
Can fix them?

**Comment by aston314** [comment]
anyone can fix it?

**Comment by aston314** [comment]
wait for fixing 1337x.

**Comment by aston314** [comment]
1337 just return :
{"data":[{"name":"The Flash 2023 HDTS 1080p x264 AAC 2GB - HushRips.","size":"2.5 GB","date":"8pm Jun. 23rd","seeders":"1764","leechers":"333","url":"https://1337x.proxyninja.org/torrent/5701517/The-Flash-2023-HDTS-1080p-x264-AAC-2GB-HushRips/","uploader":"mazemaze16"}],"time":2.792140483856201,"total":1}
