### ISSUE TITLE
yts cannot paginate/1337x has no magnet link

### ISSUE THREAD

**Issue by aston314** [Ryuk-me/Torrent-Api-py#50]
1 YTS:
The content of the first page is the same as the content of the second page.

2 1337x:
1337x has no magnet link
The json content is:
{"data":[{"name":"The Flash 2023 HDTS 1080p x264 AAC 2GB - HushRips.","size":"2.5 GB","date":"8pm Jun. 23rd","seeders":"1764","leechers":"333","url":"https://1337x.proxyninja.org/torrent/5701517/The-Flash-2023-HDTS-1080p-x264-AAC-2GB-HushRips/","uploader":"mazemaze16"}],"time":2.792140483856201,"total":1}

**Comment by Ryuk-me** [comment]
@aston314 1337x is working
![image](https://github.com/Ryuk-me/Torrent-Api-py/assets/55330971/09ac22a5-e98d-4032-96aa-2095f869c4fb)

Checking YTS issue now.

**Comment by Ryuk-me** [comment]
@aston314 YTS pagination is also working

![image](https://github.com/Ryuk-me/Torrent-Api-py/assets/55330971/9c1eb5ab-de25-4321-b3af-dadc8795d1be)

if you are running locally use `windscribe` VPN

**Comment by aston314** [comment]
> @aston314 1337x is working ![image](https://user-images.githubusercontent.com/55330971/250037243-09ac22a5-e98d-4032-96aa-2095f869c4fb.png)
> 
> Checking YTS issue now.

I deploy on http://deta.space/,1337x not work.

**Comment by aston314** [comment]
> @aston314 YTS pagination is also working
> 
> ![image](https://user-images.githubusercontent.com/55330971/250038475-9c1eb5ab-de25-4321-b3af-dadc8795d1be.png)
> 
> if you are running locally use `windscribe` VPN

The pagination does not work on Recent&Trending type.

**Comment by Ryuk-me** [comment]
@aston314 I will fix issue related on YTS and I don't know about deta issue, I will try to deploy on digital ocean and check the issue.

**Comment by aston314** [comment]
Thanks.

**Comment by Ryuk-me** [comment]
@aston314 fixed #52

**Comment by Ryuk-me** [comment]
Also, everything is working as expected on Digital Ocean.

![image](https://github.com/Ryuk-me/Torrent-Api-py/assets/55330971/ec8e65fa-7295-4a7b-bf8d-396408cf4d5f)

**Comment by aston314** [comment]
> Also, everything is working as expected on Digital Ocean.
> 
> ![image](https://user-images.githubusercontent.com/55330971/250288568-ec8e65fa-7295-4a7b-bf8d-396408cf4d5f.png)

Thank you. Unfortunately, I don't have Digital Ocean, but you can take a look at this:

https://tapi3.onrender.com/api/v1/trending?site=1337x&limit=1

Deploying on render.com is a straightforward process that you can easily try and test.
Deploying the usage of a webservice.

**Comment by Ryuk-me** [comment]
@aston314 i'll try to find the issue

**Comment by aston314** [comment]
Yes,very strange.

**Comment by Ryuk-me** [comment]
@aston314 fixed #53

**Comment by aston314** [comment]
Works great,thanks!!
