### ISSUE TITLE
YTS api

### ISSUE THREAD

**Issue by aston314** [Ryuk-me/Torrent-Api-py#55]
search :  https://yts.torrentbay.net/api/v2/list_movies.json?query_term=%20spider
recent add : https://yts.torrentbay.to/api/v2/list_movies.json?sort_by=date_added&order_by=DESC
hot : https://yts.torrentbay.net/api/v2/list_movies.json?sort_by=rating&order_by=DESC
paging: https://yts.torrentbay.net/api/v2/list_movies.json?query_term=%20spider&page=2

Can add a YTS api site?

**Comment by Ryuk-me** [comment]
@aston314 sure will add it.

**Comment by Ryuk-me** [comment]
@aston314 I'll try to add it by weekend.

**Comment by aston314** [comment]
Thanks.

**Comment by aston314** [comment]
any update?
