### ISSUE TITLE
having problem to search it's shows this message {Expecting value: line 1 column 1 (char 0)}

### ISSUE THREAD

**Issue by misershaad** [Ryuk-me/Torrent-Api-py#6]
Expecting value: line 1 column 1 (char 0)

**Comment by Ryuk-me** [comment]
can u please share the query you are trying to use 
like : `api/v1/search?site=1337x&query=avengers`

**Comment by Ryuk-me** [comment]
@misershaad u have hosted it on heroku ?

**Comment by Ryuk-me** [comment]
@yadianluffy have u added redis uri ? 

if not then get it from here https://redistogo.com/

**Comment by yadianluffy** [comment]
@Ryuk-me I don't have a redis account and I don't have a credit card for that.

**Comment by Ryuk-me** [comment]
@yadianluffy u dont need one just visit that site and at bottom u will see a free option and create an account dont put anything in website column after creating account scroll down to bottom u will see free option select it and create an instance and paste that uri to .env file `REDIS_URI=redis://redistogo:f99edf3de0cyryty324fe462@sole.redistogo.com:10393/` and u r good to go.

![redis](https://user-images.githubusercontent.com/55330971/158209889-a842d30e-1732-412b-9ef2-0e887630fab5.png)

**Comment by misershaad** [comment]
yes I have hosted it in heroku

**Comment by yadianluffy** [comment]
@Ryuk-me thank you very much for the help I really didn't see the free plan when I entered the page hahaha, dyslexia

**Comment by misershaad** [comment]
@yadianluffy then should I host it on my local computer? If I host it on my local computer then, when the computer is turned off will the API still work?

**Comment by misershaad** [comment]
I tried to install it on repl I installed the requirements manually and it was successfully installed then I set the environments and set the command "python main.py" and when I run the repl it has an error like this

Because fastapi (0.75.0) depends on starlette (0.17.1)
   and no versions of fastapi match >0.75.0,<0.76.0, fastapi (>=0.75.0,<0.76.0) requires starlette (0.17.1).
  So, because repl-python3-beta-torrent-api-py depends on both fastapi (^0.75.0) and starlette (^0.19.0), version solving failed.

  at /opt/virtualenvs/python3/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
exit status 1

I tried to install the starlette==0.17.1 but it is not working again and again what should I do now?

**Comment by Ryuk-me** [comment]
@misershaad i have mentioned that u have to install each requirement manually one by one otherwise u will face this issue

**Comment by misershaad** [comment]
I installed each requirement manually. I mentioned this in the 1st line of previous message

**Comment by misershaad** [comment]
@Ryuk-me Here is the same error hosting it on repl

**Comment by misershaad** [comment]
@Ryuk-me added in the secrets
![image](https://user-images.githubusercontent.com/91933177/158411641-778c1cdd-dbe3-4c5b-b010-68d13ec5d5be.png)
![image](https://user-images.githubusercontent.com/91933177/158411704-29173f01-c5c4-4b4f-b88f-cfee9c12236c.png)

**Comment by Ryuk-me** [comment]
@misershaad change redis_uri bro

**Comment by Ryuk-me** [comment]
it should be working 
@misershaad delete repl and add repo again and install requiremnets manually this time and get redis uri from redistogo.com and change place it in REDIS_URI environment variable

**Comment by Ryuk-me** [comment]
@misershaad host your api here https://github.com/Ryuk-me/Torrent-Api-py/commit/4b8bab97e81f71095c0b0d07f8cd669bcf894049
