### ISSUE TITLE
Frozenlist error

### ISSUE THREAD

**Issue by vpcreatz** [Ryuk-me/Torrent-Api-py#61]
Frozenlist distribution not found, it is log. Kindly update version or remove it from requirement.txt

**Comment by Ryuk-me** [comment]
@vpcreatz I have checked it is working fine, could you please send me screenshot if the issue is still there.

**Comment by MirrorBotTgram** [comment]
Frozenlist error, It say's Deploy Failed on render

`ERROR: Could not find a version that satisfies the requirement frozenlist==1.4.0 (from -r requirements.txt (line 14)) (from versions: 1.0.0a0, 1.0.0, 1.1.0, 1.1.1, 1.2.0a8, 1.2.0, 1.3.0a0, 1.3.0, 1.3.1, 1.3.3)`

Here's the screenshot.. @Ryuk-me 
![image](https://github.com/Ryuk-me/Torrent-Api-py/assets/147638750/b6c61acc-184b-46c8-b126-2323298008ea)

**Comment by Ryuk-me** [comment]
fixed
