### ISSUE TITLE
Okteto Deployment Error

### ISSUE THREAD

**Issue by missemily2022** [Ryuk-me/Torrent-Api-py#7]
![image](https://user-images.githubusercontent.com/97376138/159923132-d080db51-76d5-4aa2-8f79-49618f4f4a60.png)

**Comment by Ryuk-me** [comment]
@missemily2022 can u please share your `okteto-stack.yml` file contents

**Comment by missemily2022** [comment]
@Ryuk-me 
![image](https://user-images.githubusercontent.com/97376138/159933078-5fea4b45-8c68-47a6-8f04-7ce420a3a52b.png)

**Comment by Ryuk-me** [comment]
@missemily2022 create a dockerhub account and change `image - YOURDOCKERHUBUSERNAME/fastapi-crud:latest` in okteto-stack.yml file

**Comment by Ryuk-me** [comment]
@missemily2022 No

https://www.okteto.com/blog/building-and-deploying-a-fastapi-app-in-okteto-cloud/

**Comment by missemily2022** [comment]
@Ryuk-me Let me try !

**Comment by missemily2022** [comment]
@Ryuk-me 
![image](https://user-images.githubusercontent.com/97376138/159966475-6eed0fee-3640-4515-860e-069de2efd649.png)

**Comment by Ryuk-me** [comment]
@missemily2022 try removing image from yml file

**Comment by missemily2022** [comment]
@Ryuk-me The whole line?

**Comment by Ryuk-me** [comment]
@yes image: fastapi-crud:latest

**Comment by Ryuk-me** [comment]
@missemily2022 fixed ?

**Comment by missemily2022** [comment]
@Ryuk-me Bruh forgot to tell you but the bot deployed

It had a very different EndPoint URL : https://fastapi-missemily2022.cloud.okteto.net/

And hence it does not work
