### ISSUE TITLE
Error when deploy in okteto

### ISSUE THREAD

**Issue by alok99-git** [Ryuk-me/Torrent-Api-py#9]
Log:
https://telegra.ph/file/e6304374cfe5f70599f2d.jpg

**Comment by alok99-git** [comment]
> Remove this line `image: fastapi-crud:latest` From okteto-stack.yml file
> 
> Tell me if this works for u

Works now

**Comment by Ryuk-me** [comment]
@alok99-git fixed overall https://github.com/Ryuk-me/Torrent-Api-py/commit/b6babd7dcb850bc935518b3e3a2c20593ecf3a32
